### ISSUE TITLE
Create motor current based limit switch for intake (claw subsystem)

### ISSUE THREAD

**Issue by OneGneissGuy** [FRC701/Brokkr-2023#17]
Currently a 5 second timer is being used to halt the intake motor. This approach can result in running too long and overshooting when an item is captured quickly or not run long enough and time out if there is difficulty capturing cone. 

The intake should  run only long enough to capture and secure the cone and no longer. A current based limit switch will monitor the motor current and stop the motor only when a predetermined current (above a baseline is reached). The limit would be triggered when the motor stalls after capturing a cone or box.  To avoid false triggers, consider using the time integral of current, rather than a current limit in amps. Need to experiment to determine the baseline current of running the motors during intake with and without an item.

**Comment by duane701** [comment]
Thoughts for an implementation:

1. Write a new command for the Claw subsystem. Perhaps called `ClawSpinCurrentLimit`.
2. The command Ends() when the motor current exceeds some constant.
3. Perhaps the current should be exceed the limit for 300 milliseconds, so a timer is needed.

**Comment by duane701** [comment]
Closed in previous pull request
